name: Deploy Lambdas

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare deployment package
      run: |
        for dir in lambdas/*; do
          # Verifica si el archivo 'app.py' existe antes de crear el archivo ZIP
          if [ -f "$dir/app.py" ]; then
            # Crea el archivo ZIP en la raíz sin subdirectorios
            zip -j "$dir/package.zip" "$dir/app.py"
          else
            echo "Archivo app.py no encontrado en $dir"
          fi
        done

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        for dir in lambdas/*; do
          FUNCTION_NAME=$(basename "$dir")
          # Subir el archivo ZIP directamente
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://"$dir/package.zip"
        done
